export let htmlData = [
    {
        "short": "para",
        "label": "science",
        "hed": "How far away is the sun? They went on a perilous journey to find out",
        "dek": "Illustrator",
        "link": "https://www.nationalgeographic.com/premium/article/perilous-17th-century-french-journey-find-distance-to-sun-cassini-richer",
        "asset": "background-image",
        "color": "white",
        "role": "I led the development, design and research of the project. I created an accurate 3D model of the solar system, using data from NASA and orbital mechanic formulas.",
        "lvl": 3,
    },
    {
        "short": "ast",
        "label": "science",
        "hed": "These 5 asteroids pose the greatest risk to Earth",
        "dek": "ThreeJS, TheatreJS, Blender, Python, Illustrator",
        "link": "https://www.nationalgeographic.com/premium/graphics/five-asteroids-could-hit-earth",
        "asset": "video",
        "color": "black",
        "role": "I led the development, design and research of the project. I created an accurate 3D model of the solar system, using data from NASA and orbital mechanic formulas.",
        "lvl": 1
    },
    {
        "short": "mummy",
        "label": "history",
        "hed": "Step inside an ancient mummfication workshop",
        "dek": "ThreeJS, TheatreJS, Blender, Illustrator, Photoshop, Meshlab, CloudCompare",
        "link": "https://www.nationalgeographic.com/premium/graphics/egypt-mummy-saqqara-excavation-golden-age-feature",
        "asset": "background-image",
        "color": "black",
        "role": "I led the development and design of the project. I developed a reusable and extendable 3D project pipeline and workflow centered on ThreeJS, TheatreJS, and a custom labelling method. I created the 3D model with raw point cloud data in Meshlab and CloudCompare, and I optimized the model for digital usage in Blender. I made the cutaway 3D workshop. I also worked on the print magazine version, making a highly detailed and refined 3D model in Blender.",
        "lvl": 1
    },
    {
        "short": "birth",
        "label": "History",
        "hed": "Smaller families, starting later",
        "dek": "Front-end dev, D3",
        "link": "https://www.nationalgeographic.com/premium/graphics/us-fertility-rate-older-and-lower",
        "asset": "background-image",
        "color": "white",
        "role": "I led the developement of the project, which is a major event for Nat Geo involving departments across the organization.",
        "lvl": 1
    },
    {
        "short": "monarch",
        "label": "Animals",
        "hed": "Monarchs are actually toxic—and 5 other ways the butterflies amaze us",
        "dek": "Front-end dev, FFmpeg",
        "link": "https://www.nationalgeographic.com/premium/graphics/five-ways-monarch-butterflies-amaze",
        "asset": "background-image",
        "color": "white",
        "role": "I led the developement of the project, which is a major event for Nat Geo involving departments across the organization.",
        "lvl": 2
    },
    {
        "short": "yip",
        "label": "Photo",
        "hed": "Pictures of the Year 2023",
        "dek": "Front-end dev",
        "link": "https://www.nationalgeographic.com/premium/graphics/pictures-of-the-year-2023",
        "asset": "background-image",
        "color": "black",
        "role": "I led the developement of the project, which is a major event for Nat Geo involving departments across the organization.",
        "lvl": 1
    },
        {
        "short": "al",
        "label": "history",
        "hed": "The dazzling details of Spain's Alhambra",
        "dek": "Front-end dev, After Effects, Illustrator",
        "link": "https://www.nationalgeographic.com/premium/graphics/details-of-spains-alhambra",
        "asset": "background-image",
        "color": "white",
        "role": "I developed the project and animated the illustrations for many of the videos.",
        "lvl": 1  },
    {
        "short": "ele",
        "label": "animals",
        "hed": "Elephants are learning to live with us. Can we do the same?",
        "dek": "Front-end dev",
        "link": "https://www.nationalgeographic.com/premium/graphics/asian-elephants-behavior-coexistence-survival-feature",
        "asset": "background-image",
        "color": "black",
        "role": "As a one developer of a larger team, I implemented bespoke features and designs that worked across all devices. I solved issues around the complex behavior for images being shrunk down as a user scrolls.",
        "lvl": 2
    },
    {
        "short": "longevity",
        "label": "animals",
        "hed": "How do some animals defy age? In nature, size matters",
        "dek": "After Effects, JavaScript, FFmpeg, Illustrator, Photoshop",
        "link": "https://www.nationalgeographic.com/magazine/graphics/animal-aging-longevity",
        "asset": "video",
        "color": "white",
        "role": "I converted the assets from print to digital. I animated the intro video and problem-solved a cross-browser method of handling transparent video.",
        "lvl": 2
    },
    {
        "short": "venus",
        "label": "science",
        "hed": "Venus is volcanically alive, stunning new find shows",
        "dek": "Illustrator, qGIS",
        "link": "https://www.nationalgeographic.com/science/article/venus-is-volcanically-alive",
        "asset": "background-image",
        "color": "black",
        "role": "Graphics editor",
        "lvl": 3
    },
    {
        "short": "stingray",
        "label": "animals",
        "hed": "A wildlife first: World's biggest ocean stingray tagged in the wild",
        "dek": "Illustrator",
        "link": "https://www.nationalgeographic.com/animals/article/worlds-biggest-ocean-stingray-tagged-for-first-time",
        "asset": "background-image",
        "color": "white",
        "role": "Graphics editor",
        "lvl": 3
    },
    {
        "short": "hawaii",
        "label": "science",
        "hed": "Hawaii's volcanic underbelly in stunning detail",
        "dek": "Blender, Illustrator, qGIS, FFmpeg, JavaScript",
        "link": "https://www.nationalgeographic.com/science/article/scientists-mapped-hawaiis-volcanic-underbelly-in-stunning-detail",
        "asset": "video",
        "color": "black",
        "role": "With a tight two-week deadline, I learned how to combine GIS and Blender without any prior experience in 3D GIS. I also jerry-rigged Blender so it could handle large point cloud GIS data.",
        "lvl": 3
    },
    {
        "short": "starmap",
        "label": "science",
        "hed": "The world's oldest map of the night sky was amazingly accurate",
        "dek": "Illustrator",
        "link": "https://www.nationalgeographic.com/magazine/article/worlds-oldest-map-of-night-sky-amazingly-accurate",
        "asset": "background-image",
        "color": "black",
        "role": "Graphics editor",
        "lvl": 3
    },
    {
        "short": "tut",
        "label": "history",
        "hed": "See the enduring power of King Tut as never before",
        "dek": "After Effects, Illustrator, JavaScript",
        "link": "https://www.nationalgeographic.com/magazine/graphics/see-the-enduring-power-of-king-tut-as-never-before-feature",
        "asset": "video",
        "color": "black",
        "role": "I learned After Effects and keyframed many of the artifact animations in the project.",
        "lvl": 2
    },
    {
        "short": "artemis",
        "label": "science",
        "hed": "A visual guide of NASA's plan to get back to the moon",
        "dek": "Illustrator, qGIS",
        "link": "https://www.nationalgeographic.com/magazine/graphics/a-visual-guide-of-nasas-plan-to-get-back-to-the-moon",
        "asset": "background-image",
        "color": "black",
        "role": "This was my first project I lead for Nat Geo. I used Illustrator to creat all the stylized assets, including a dozen other detailed rocket models that were scrapped during development. I collaborated with an outside researcher in addition to doing my own research.",
        "lvl": 1
    },
    {
        "short": "wells",
        "label": "environment",
        "hed": "To find old methane-leaking oil wells, researchers look to history",
        "dek": "qGIS, Map Publisher, GDAL, Illustrator",
        "link": "https://www.nationalgeographic.com/environment/article/to-find-old-methane-leaking-oil-wells-researchers-look-to-history",
        "asset": "background-image",
        "color": "white",
        "role": "I taught myself the basics of GIS, creating my own shaded relief. I also learned a solid qGIS-to-MapPublisher workflow.",
        "lvl": 3
    },
    {
        "short": "stonehenge",
        "label": "history",
        "hed": "See how stones, strength, and smarts built Stonehenge",
        "dek": "Illustrator",
        "link": "https://www.nationalgeographic.com/magazine/graphics/see-how-stones-strength-and-smarts-built-stonehenge-feature",
        "asset": "video",
        "color": "black",
        "role": "I handled all the labelling for the project.",
        "lvl": 2
    },
];